### ISSUE TITLE
Add known VHE sources in the Cygnus region

### ISSUE THREAD

**Issue by cdeil** [gammasky/cta-dc#24]
@jknodlseder pointed out via email that in the current CTA 1DC GPS model is missing the known VHE sources in the Cygnus region, and that the Kashiwa GPS model contained the following four sources:
```
  <source name="Fermi cocoon" type="ExtendedSource">
    <spectrum type="PowerLaw">
      <parameter name="Prefactor" value="1.3"  scale="1e-17" min="0.001" max="1000" free="1" />
      <parameter name="Index"     value="-2.3" scale="1"     min="-10"   max="10"   free="1" />
      <parameter name="Scale"     value="1"    scale="1e+06" min="0.001" max="1000" free="0" />
    </spectrum>
    <spatialModel type="GaussFunction">
      <parameter name="GLON"  value="79.6" scale="1" min="0"    max="360"  free="1" />
      <parameter name="GLAT"  value="1.4"  scale="1" min="-90"  max="90"   free="1" />
      <parameter name="Sigma" value="2.0"  scale="1" min="0.01" max="10.0" free="1" />
    </spatialModel>
  </source>
  <source name="SNR G78.2+2.1" type="ExtendedSource">
    <spectrum type="ExpCutoff">
      <parameter name="Prefactor" value="4.27"  scale="1e-18" min="0.001" max="1000" free="1" />
      <parameter name="Index"     value="-2.42" scale="1"     min="-10"   max="10"   free="1" />
      <parameter name="Scale"     value="1"     scale="1e+06" min="0.001" max="1000" free="0" />
      <parameter name="Cutoff"    scale="1e6"   value="1.0"   min="0.01"  max="1000" free="1"/>
    </spectrum>
    <spatialModel type="DiskFunction">
      <parameter name="GLON"   scale="1.0" value="78.24" min="-360" max="360" free="1"/>
      <parameter name="GLAT"   scale="1.0" value="2.20"  min="-90"  max="90"  free="1"/>
      <parameter name="Radius" scale="1.0" value="0.63"  min="0.01" max="10"  free="1"/>
    </spatialModel>
  </source>
  <source name="VER J2019+407 (bis)" type="ExtendedSource">
    <spectrum type="ExpCutoff">
      <parameter name="Prefactor" value="1.5"   scale="1e-18" min="0.001" max="1000" free="1" />
      <parameter name="Index"     value="-2.37" scale="1"     min="-10"   max="10"   free="1" />
      <parameter name="Scale"     value="1"     scale="1e+06" min="0.001" max="1000" free="0" />
      <parameter name="Cutoff"    scale="1e6"   value="40.0"  min="0.01"  max="1000" free="1"/>
    </spectrum>
    <spatialModel type="GaussFunction">
      <parameter name="GLON"  value="78.1662" scale="1" min="0"    max="360"  free="1" />
      <parameter name="GLAT"  value="2.6241"  scale="1" min="-90"  max="90"   free="1" />
      <parameter name="Sigma" value="0.23"    scale="1" min="0.01" max="10.0" free="1" />
    </spatialModel>
  </source>
  <source name="TeV J2032+4130 (bis)" type="ExtendedSource">
    <spectrum type="ExpCutoff">
      <parameter name="Prefactor" value="9.5"  scale="1e-19" min="0.001" max="1000" free="1" />
      <parameter name="Index"     value="-2.1" scale="1"     min="-10"   max="10"   free="1" />
      <parameter name="Scale"     value="1"    scale="1e+06" min="0.001" max="1000" free="0" />
      <parameter name="Cutoff"    scale="1e6"  value="40.0"  min="0.01"  max="1000" free="1"/>
    </spectrum>
    <spatialModel type="GaussFunction">
      <parameter name="GLON"  value="80.279" scale="1" min="0"    max="360"  free="1" />
      <parameter name="GLAT"  value="1.042"  scale="1" min="-90"  max="90"   free="1" />
      <parameter name="Sigma" value="0.083"  scale="1" min="0.01" max="10.0" free="1" />
    </spatialModel>
  </source>
```

---

The CTA 1DC GPS bright source model is derived from gamma-cat, and indeed we were missing data entry for these sources so far:
http://gamma-sky.net/#/map?target=76.398,3.805&fov=44.461&marker=tev

A week ago @GernotMaier commented that he could do the data entry for the following two papers / four sources soon:
```
MGRO J2019+38: 2014/2014ApJ...788…78A/
TeV 2032: 2014/2014ApJ...783…16A/
VER J2019+407 (g-cygni): 2013/2013ApJ...770…93A
VER J2016+371: 2014/2014ApJ...788…78A/
```

This issue is a reminder that we should add this, and to compare against the sources / parameters in the older Cygnus model (the XML file pasted here).

@GernotMaier - If you make the PR to gamma-cat, I'll re-run the scripts that update the CTA 1DC GPS sky model XML file in this repo.

**Comment by GernotMaier** [comment]
For http://gamma-sky.net/#/cat/tev/142, the spectrum is in 

2014ApJ...788...78A/tev-000143-sed.ecsv

http://gamma-sky.net/#/cat/tev/145 is duplicated? http://gamma-sky.net/#/cat/tev/146
(one is the HEGRA detection, the other one the MILAGRO detection)

The SED from VERITAS can be found here:

https://github.com/gammapy/gamma-cat/tree/master/input/data/2014/2014ApJ...783...16A

**Comment by cdeil** [comment]
> For http://gamma-sky.net/#/cat/tev/142, the spectrum is in 2014ApJ...788...78A/tev-000143-sed.ecsv

Great! So VERITAS data entry for the Cygnus region is complete now.

> http://gamma-sky.net/#/cat/tev/145 is duplicated? http://gamma-sky.net/#/cat/tev/146
(one is the HEGRA detection, the other one the MILAGRO detection)

I see:
* http://gamma-cat.readthedocs.io/use/sources/145.html
* http://gamma-cat.readthedocs.io/use/sources/146.html

TeVCat has this as two sources as well.

Of course we could remove the MILAGRO source, if it's clearly matching the HEGRA/VERITAS source. We'll have that question for many other Galactic sources, when to put a separate one where MILAGRO or HAWC sees something similar.

I'm closing this issue now, keeping as-is. @GernotMaier - if you think the MILAGRO source http://gamma-cat.readthedocs.io/use/sources/145.html should be removed from gamma-cat, and instead a note added to http://gamma-cat.readthedocs.io/use/sources/146.html that MILAGRO has seen that source, please open an issue in the gamma-cat tracker and link to this discussion.
